from unittest import TestCase

from lib.input import clean_input
from main import solve_part_one

class Test(TestCase):
    def test_solve_part_one(self):
        lines = clean_input('''
                ............
                ........0...
                .....0......
                .......0....
                ....0.......
                ......A.....
                ............
                ............
                ........A...
                .........A..
                ............
                ............
                ''')

        expected = 14
        actual = solve_part_one(lines)

        self.assertEqual(expected, actual)
